/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { InsuranceFund } from './InsuranceFund';
export type { InsuranceFundDeployer } from './InsuranceFundDeployer';
