/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from 'ethers';
import { Provider, TransactionRequest } from '@ethersproject/providers';
import type {
  Uint32L8ArrayLib,
  Uint32L8ArrayLibInterface,
} from '../Uint32L8ArrayLib';

const _abi = [
  {
    inputs: [
      {
        internalType: 'uint32',
        name: 'element',
        type: 'uint32',
      },
    ],
    name: 'U32L8_IllegalElement',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'uint32',
        name: 'element',
        type: 'uint32',
      },
    ],
    name: 'U32L8_NoSpaceLeftToInsert',
    type: 'error',
  },
];

const _bytecode =
  '0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122020ff350025ca771a53a496163843db6834c0c2980ed8215c306909390468b77e64736f6c634300080d0033';

type Uint32L8ArrayLibConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: Uint32L8ArrayLibConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Uint32L8ArrayLib__factory extends ContractFactory {
  constructor(...args: Uint32L8ArrayLibConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
    this.contractName = 'Uint32L8ArrayLib';
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Uint32L8ArrayLib> {
    return super.deploy(overrides || {}) as Promise<Uint32L8ArrayLib>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): Uint32L8ArrayLib {
    return super.attach(address) as Uint32L8ArrayLib;
  }
  connect(signer: Signer): Uint32L8ArrayLib__factory {
    return super.connect(signer) as Uint32L8ArrayLib__factory;
  }
  static readonly contractName: 'Uint32L8ArrayLib';
  public readonly contractName: 'Uint32L8ArrayLib';
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): Uint32L8ArrayLibInterface {
    return new utils.Interface(_abi) as Uint32L8ArrayLibInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Uint32L8ArrayLib {
    return new Contract(address, _abi, signerOrProvider) as Uint32L8ArrayLib;
  }
}
