/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers';
import type { FunctionFragment, Result } from '@ethersproject/abi';
import type { Listener, Provider } from '@ethersproject/providers';
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from '../../../common';

export interface ClearingHouseExtsloadTestInterface extends utils.Interface {
  functions: {
    'check_pools_vPool_and_settings_twapDuration(address,uint32)': FunctionFragment;
    'pools_settings(address,uint32)': FunctionFragment;
    'pools_vPool(address,uint32)': FunctionFragment;
    'pools_vPool_and_settings_twapDuration(address,uint32)': FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | 'check_pools_vPool_and_settings_twapDuration'
      | 'pools_settings'
      | 'pools_vPool'
      | 'pools_vPool_and_settings_twapDuration'
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: 'check_pools_vPool_and_settings_twapDuration',
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: 'pools_settings',
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: 'pools_vPool',
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: 'pools_vPool_and_settings_twapDuration',
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: 'check_pools_vPool_and_settings_twapDuration',
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: 'pools_settings',
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: 'pools_vPool',
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: 'pools_vPool_and_settings_twapDuration',
    data: BytesLike
  ): Result;

  events: {};
}

export interface ClearingHouseExtsloadTest extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ClearingHouseExtsloadTestInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    check_pools_vPool_and_settings_twapDuration(
      clearingHouse: string,
      poolId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    pools_settings(
      clearingHouse: string,
      poolId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [number, number, number, number, boolean, boolean, string] & {
        initialMarginRatioBps: number;
        maintainanceMarginRatioBps: number;
        maxVirtualPriceDeviationRatioBps: number;
        twapDuration: number;
        isAllowedForTrade: boolean;
        isCrossMargined: boolean;
        oracle: string;
      }
    >;

    pools_vPool(
      clearingHouse: string,
      poolId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string] & { vPool: string }>;

    pools_vPool_and_settings_twapDuration(
      clearingHouse: string,
      poolId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, number] & { vPool: string; twapDuration: number }>;
  };

  check_pools_vPool_and_settings_twapDuration(
    clearingHouse: string,
    poolId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  pools_settings(
    clearingHouse: string,
    poolId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [number, number, number, number, boolean, boolean, string] & {
      initialMarginRatioBps: number;
      maintainanceMarginRatioBps: number;
      maxVirtualPriceDeviationRatioBps: number;
      twapDuration: number;
      isAllowedForTrade: boolean;
      isCrossMargined: boolean;
      oracle: string;
    }
  >;

  pools_vPool(
    clearingHouse: string,
    poolId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  pools_vPool_and_settings_twapDuration(
    clearingHouse: string,
    poolId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[string, number] & { vPool: string; twapDuration: number }>;

  callStatic: {
    check_pools_vPool_and_settings_twapDuration(
      clearingHouse: string,
      poolId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, number] & { vPool: string; twapDuration: number }>;

    pools_settings(
      clearingHouse: string,
      poolId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [number, number, number, number, boolean, boolean, string] & {
        initialMarginRatioBps: number;
        maintainanceMarginRatioBps: number;
        maxVirtualPriceDeviationRatioBps: number;
        twapDuration: number;
        isAllowedForTrade: boolean;
        isCrossMargined: boolean;
        oracle: string;
      }
    >;

    pools_vPool(
      clearingHouse: string,
      poolId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    pools_vPool_and_settings_twapDuration(
      clearingHouse: string,
      poolId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, number] & { vPool: string; twapDuration: number }>;
  };

  filters: {};

  estimateGas: {
    check_pools_vPool_and_settings_twapDuration(
      clearingHouse: string,
      poolId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    pools_settings(
      clearingHouse: string,
      poolId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pools_vPool(
      clearingHouse: string,
      poolId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pools_vPool_and_settings_twapDuration(
      clearingHouse: string,
      poolId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    check_pools_vPool_and_settings_twapDuration(
      clearingHouse: string,
      poolId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    pools_settings(
      clearingHouse: string,
      poolId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pools_vPool(
      clearingHouse: string,
      poolId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pools_vPool_and_settings_twapDuration(
      clearingHouse: string,
      poolId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
