/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IExchange__factory } from './IExchange__factory';
export { IStableSwap__factory } from './IStableSwap__factory';
