/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as swapManagerSol from './SwapManager.sol';
export type { swapManagerSol };
export type { DnGmxJuniorVaultHelpers } from './DnGmxJuniorVaultHelpers';
