/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BatchedLoopTest } from './BatchedLoopTest';
export type { BatchedLoopTest2 } from './BatchedLoopTest2';
