/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DnGmxJuniorVaultStorage } from './DnGmxJuniorVaultStorage';
export type { IDebtToken } from './IDebtToken';
